CREATE USER esystem IDENTIFIED BY 'password';
GRANT PROCESS, RELOAD, SHOW DATABASES ON *.* TO 'esystem';

CREATE USER eadmin IDENTIFIED BY 'password';
GRANT
  ALTER, ALTER ROUTINE,
  CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW,
  DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, SELECT, SHOW VIEW, TRIGGER, UPDATE
ON esample.* TO 'eadmin';

CREATE USER eapp IDENTIFIED BY 'password';
GRANT
  ALTER, ALTER ROUTINE,
  CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW,
  DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, SELECT, SHOW VIEW, TRIGGER, UPDATE
ON esample.* TO 'eapp';

