version: '3'

services:

  db:
    build: "./db"
    container_name: "esample-db"
    ports:
      - 3306:3306
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/mysql"
      - "./db/log:/var/log/mysql"
    environment:
      MYSQL_DATABASE: esample
      MYSQL_ROOT_PASSWORD: password

  ap:
    build: "./ap"
    container_name: "esample-ap"
    ports: 
      - "80:1323"
    volumes:
      - "./ap:/go/src/ap"
    depends_on:
      - db

